repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        files: ".*\\.yaml$"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format


  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: ["--write"]
        files: "dashboard_frontend/src.*\\.(js|jsx|ts|tsx|json|css|scss|md|html)$"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
        name: eslint
        files: "dashboard_frontend/src.*\\.(js|jsx|ts|tsx)$"
        args: ["--fix", "--no-ignore"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: "examples|docs/examples|tests/data"
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude: "examples|docs/examples|tests/data"
