repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        files: ".*\\.yaml$"
      - id: end-of-file-fixer
        exclude: "chronos2/dashboard_backend/examples|chronos2/dashboard_backend/tests/data"
      - id: trailing-whitespace
        files: "chronos2/dashboard_backend/.*\\.py$"
        exclude: "chronos2/dashboard_backend/examples|chronos2/dashboard_backend/tests/data"
      - id: check-added-large-files
        files: "chronos2/dashboard_backend/.*"
      - id: check-toml
        files: "chronos2/dashboard_backend/.*\\.toml$"

  # Code formatting for Python (backend)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: "chronos2/dashboard_backend/.*\\.py$"

  # Import sorting for Python (backend)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]
        files: "chronos2/dashboard_backend/.*\\.py$"
