services:
  edge_server:
    build:
      context: ./edge_server
    privileged: true
    container_name: edge_server
    networks:
      - traefik-public
    ports:
      - "5171:5171"
  dashboard_frontend:
    ports:
      - "5173:5173"

  dashboard_backend:
    ports:
      - "5172:5172"

  postgres:
    ports:
      - "5400:5432"
