SETPOINT_LOOKUP_DATA = [
    {
        "id": 1,
        "wind_chill": -30,
        "setpoint": 100.0,
        "avg_wind_chill": -30,
        "setpoint_offset": 0,
    },
    {
        "id": 2,
        "wind_chill": -29,
        "setpoint": 100.0,
        "avg_wind_chill": -29,
        "setpoint_offset": 0,
    },
    {
        "id": 3,
        "wind_chill": -28,
        "setpoint": 100.0,
        "avg_wind_chill": -28,
        "setpoint_offset": 0,
    },
    {
        "id": 4,
        "wind_chill": -27,
        "setpoint": 100.0,
        "avg_wind_chill": -27,
        "setpoint_offset": 0,
    },
    {
        "id": 5,
        "wind_chill": -26,
        "setpoint": 100.0,
        "avg_wind_chill": -26,
        "setpoint_offset": 0,
    },
    {
        "id": 6,
        "wind_chill": -25,
        "setpoint": 100.0,
        "avg_wind_chill": -25,
        "setpoint_offset": 0,
    },
    {
        "id": 7,
        "wind_chill": -24,
        "setpoint": 100.0,
        "avg_wind_chill": -24,
        "setpoint_offset": 0,
    },
    {
        "id": 8,
        "wind_chill": -23,
        "setpoint": 100.0,
        "avg_wind_chill": -23,
        "setpoint_offset": 0,
    },
    {
        "id": 9,
        "wind_chill": -22,
        "setpoint": 100.0,
        "avg_wind_chill": -22,
        "setpoint_offset": 0,
    },
    {
        "id": 10,
        "wind_chill": -21,
        "setpoint": 100.0,
        "avg_wind_chill": -21,
        "setpoint_offset": 0,
    },
    {
        "id": 11,
        "wind_chill": -20,
        "setpoint": 100.0,
        "avg_wind_chill": -20,
        "setpoint_offset": 0,
    },
    {
        "id": 12,
        "wind_chill": -19,
        "setpoint": 100.0,
        "avg_wind_chill": -19,
        "setpoint_offset": 0,
    },
    {
        "id": 13,
        "wind_chill": -18,
        "setpoint": 100.0,
        "avg_wind_chill": -18,
        "setpoint_offset": 0,
    },
    {
        "id": 14,
        "wind_chill": -17,
        "setpoint": 100.0,
        "avg_wind_chill": -17,
        "setpoint_offset": 0,
    },
    {
        "id": 15,
        "wind_chill": -16,
        "setpoint": 100.0,
        "avg_wind_chill": -16,
        "setpoint_offset": 0,
    },
    {
        "id": 16,
        "wind_chill": -15,
        "setpoint": 100.0,
        "avg_wind_chill": -15,
        "setpoint_offset": 0,
    },
    {
        "id": 17,
        "wind_chill": -14,
        "setpoint": 100.0,
        "avg_wind_chill": -14,
        "setpoint_offset": 0,
    },
    {
        "id": 18,
        "wind_chill": -13,
        "setpoint": 100.0,
        "avg_wind_chill": -13,
        "setpoint_offset": 0,
    },
    {
        "id": 19,
        "wind_chill": -12,
        "setpoint": 100.0,
        "avg_wind_chill": -12,
        "setpoint_offset": 0,
    },
    {
        "id": 20,
        "wind_chill": -11,
        "setpoint": 100.0,
        "avg_wind_chill": -11,
        "setpoint_offset": 0,
    },
    {
        "id": 21,
        "wind_chill": -10,
        "setpoint": 100.0,
        "avg_wind_chill": -10,
        "setpoint_offset": 0,
    },
    {
        "id": 22,
        "wind_chill": -9,
        "setpoint": 100.0,
        "avg_wind_chill": -9,
        "setpoint_offset": 0,
    },
    {
        "id": 23,
        "wind_chill": -8,
        "setpoint": 100.0,
        "avg_wind_chill": -8,
        "setpoint_offset": 0,
    },
    {
        "id": 24,
        "wind_chill": -7,
        "setpoint": 100.0,
        "avg_wind_chill": -7,
        "setpoint_offset": 0,
    },
    {
        "id": 25,
        "wind_chill": -6,
        "setpoint": 100.0,
        "avg_wind_chill": -6,
        "setpoint_offset": 0,
    },
    {
        "id": 26,
        "wind_chill": -5,
        "setpoint": 100.0,
        "avg_wind_chill": -5,
        "setpoint_offset": 0,
    },
    {
        "id": 27,
        "wind_chill": -4,
        "setpoint": 100.0,
        "avg_wind_chill": -4,
        "setpoint_offset": 0,
    },
    {
        "id": 28,
        "wind_chill": -3,
        "setpoint": 100.0,
        "avg_wind_chill": -3,
        "setpoint_offset": 0,
    },
    {
        "id": 29,
        "wind_chill": -2,
        "setpoint": 100.0,
        "avg_wind_chill": -2,
        "setpoint_offset": 0,
    },
    {
        "id": 30,
        "wind_chill": -1,
        "setpoint": 100.0,
        "avg_wind_chill": -1,
        "setpoint_offset": 0,
    },
    {
        "id": 31,
        "wind_chill": 0,
        "setpoint": 100.0,
        "avg_wind_chill": 0,
        "setpoint_offset": 0,
    },
    {
        "id": 32,
        "wind_chill": 1,
        "setpoint": 100.0,
        "avg_wind_chill": 1,
        "setpoint_offset": 0,
    },
    {
        "id": 33,
        "wind_chill": 2,
        "setpoint": 100.0,
        "avg_wind_chill": 2,
        "setpoint_offset": 0,
    },
    {
        "id": 34,
        "wind_chill": 3,
        "setpoint": 100.0,
        "avg_wind_chill": 3,
        "setpoint_offset": 0,
    },
    {
        "id": 35,
        "wind_chill": 4,
        "setpoint": 100.0,
        "avg_wind_chill": 4,
        "setpoint_offset": 0,
    },
    {
        "id": 36,
        "wind_chill": 5,
        "setpoint": 100.0,
        "avg_wind_chill": 5,
        "setpoint_offset": 0,
    },
    {
        "id": 37,
        "wind_chill": 6,
        "setpoint": 100.0,
        "avg_wind_chill": 6,
        "setpoint_offset": 0,
    },
    {
        "id": 38,
        "wind_chill": 7,
        "setpoint": 100.0,
        "avg_wind_chill": 7,
        "setpoint_offset": 0,
    },
    {
        "id": 39,
        "wind_chill": 8,
        "setpoint": 100.0,
        "avg_wind_chill": 8,
        "setpoint_offset": 0,
    },
    {
        "id": 40,
        "wind_chill": 9,
        "setpoint": 100.0,
        "avg_wind_chill": 9,
        "setpoint_offset": 0,
    },
    {
        "id": 41,
        "wind_chill": 10,
        "setpoint": 100.0,
        "avg_wind_chill": 10,
        "setpoint_offset": 0,
    },
    {
        "id": 42,
        "wind_chill": 11,
        "setpoint": 99.5,
        "avg_wind_chill": 11,
        "setpoint_offset": 0,
    },
    {
        "id": 43,
        "wind_chill": 12,
        "setpoint": 99.0,
        "avg_wind_chill": 12,
        "setpoint_offset": 0,
    },
    {
        "id": 44,
        "wind_chill": 13,
        "setpoint": 98.5,
        "avg_wind_chill": 13,
        "setpoint_offset": 0,
    },
    {
        "id": 45,
        "wind_chill": 14,
        "setpoint": 98.0,
        "avg_wind_chill": 14,
        "setpoint_offset": 0,
    },
    {
        "id": 46,
        "wind_chill": 15,
        "setpoint": 97.5,
        "avg_wind_chill": 15,
        "setpoint_offset": 0,
    },
    {
        "id": 47,
        "wind_chill": 16,
        "setpoint": 97.0,
        "avg_wind_chill": 16,
        "setpoint_offset": 0,
    },
    {
        "id": 48,
        "wind_chill": 17,
        "setpoint": 96.5,
        "avg_wind_chill": 17,
        "setpoint_offset": 0,
    },
    {
        "id": 49,
        "wind_chill": 18,
        "setpoint": 96.0,
        "avg_wind_chill": 18,
        "setpoint_offset": 0,
    },
    {
        "id": 50,
        "wind_chill": 19,
        "setpoint": 95.5,
        "avg_wind_chill": 19,
        "setpoint_offset": 0,
    },
    {
        "id": 51,
        "wind_chill": 20,
        "setpoint": 95.0,
        "avg_wind_chill": 20,
        "setpoint_offset": 0,
    },
    {
        "id": 52,
        "wind_chill": 21,
        "setpoint": 94.5,
        "avg_wind_chill": 21,
        "setpoint_offset": 0,
    },
    {
        "id": 53,
        "wind_chill": 22,
        "setpoint": 94.0,
        "avg_wind_chill": 22,
        "setpoint_offset": 0,
    },
    {
        "id": 54,
        "wind_chill": 23,
        "setpoint": 93.5,
        "avg_wind_chill": 23,
        "setpoint_offset": 0,
    },
    {
        "id": 55,
        "wind_chill": 24,
        "setpoint": 93.0,
        "avg_wind_chill": 24,
        "setpoint_offset": 0,
    },
    {
        "id": 56,
        "wind_chill": 25,
        "setpoint": 92.5,
        "avg_wind_chill": 25,
        "setpoint_offset": 0,
    },
    {
        "id": 57,
        "wind_chill": 26,
        "setpoint": 92.0,
        "avg_wind_chill": 26,
        "setpoint_offset": 0,
    },
    {
        "id": 58,
        "wind_chill": 27,
        "setpoint": 91.5,
        "avg_wind_chill": 27,
        "setpoint_offset": 0,
    },
    {
        "id": 59,
        "wind_chill": 28,
        "setpoint": 91.0,
        "avg_wind_chill": 28,
        "setpoint_offset": 0,
    },
    {
        "id": 60,
        "wind_chill": 29,
        "setpoint": 90.5,
        "avg_wind_chill": 29,
        "setpoint_offset": 0,
    },
    {
        "id": 61,
        "wind_chill": 30,
        "setpoint": 90.0,
        "avg_wind_chill": 30,
        "setpoint_offset": 0,
    },
    {
        "id": 62,
        "wind_chill": 31,
        "setpoint": 89.5,
        "avg_wind_chill": 31,
        "setpoint_offset": 0,
    },
    {
        "id": 63,
        "wind_chill": 32,
        "setpoint": 89.0,
        "avg_wind_chill": 32,
        "setpoint_offset": 0,
    },
    {
        "id": 64,
        "wind_chill": 33,
        "setpoint": 88.5,
        "avg_wind_chill": 33,
        "setpoint_offset": 0,
    },
    {
        "id": 65,
        "wind_chill": 34,
        "setpoint": 88.0,
        "avg_wind_chill": 34,
        "setpoint_offset": 0,
    },
    {
        "id": 66,
        "wind_chill": 35,
        "setpoint": 87.5,
        "avg_wind_chill": 35,
        "setpoint_offset": 0,
    },
    {
        "id": 67,
        "wind_chill": 36,
        "setpoint": 87.0,
        "avg_wind_chill": 36,
        "setpoint_offset": 0,
    },
    {
        "id": 68,
        "wind_chill": 37,
        "setpoint": 86.5,
        "avg_wind_chill": 37,
        "setpoint_offset": 0,
    },
    {
        "id": 69,
        "wind_chill": 38,
        "setpoint": 86.0,
        "avg_wind_chill": 38,
        "setpoint_offset": 0,
    },
    {
        "id": 70,
        "wind_chill": 39,
        "setpoint": 85.5,
        "avg_wind_chill": 39,
        "setpoint_offset": 0,
    },
    {
        "id": 71,
        "wind_chill": 40,
        "setpoint": 85.0,
        "avg_wind_chill": 40,
        "setpoint_offset": 0,
    },
    {
        "id": 72,
        "wind_chill": 41,
        "setpoint": 84.5,
        "avg_wind_chill": 41,
        "setpoint_offset": 0,
    },
    {
        "id": 73,
        "wind_chill": 42,
        "setpoint": 84.0,
        "avg_wind_chill": 42,
        "setpoint_offset": 0,
    },
    {
        "id": 74,
        "wind_chill": 43,
        "setpoint": 83.5,
        "avg_wind_chill": 43,
        "setpoint_offset": 0,
    },
    {
        "id": 75,
        "wind_chill": 44,
        "setpoint": 83.0,
        "avg_wind_chill": 44,
        "setpoint_offset": 0,
    },
    {
        "id": 76,
        "wind_chill": 45,
        "setpoint": 82.5,
        "avg_wind_chill": 45,
        "setpoint_offset": 0,
    },
    {
        "id": 77,
        "wind_chill": 46,
        "setpoint": 82.0,
        "avg_wind_chill": 46,
        "setpoint_offset": 0,
    },
    {
        "id": 78,
        "wind_chill": 47,
        "setpoint": 81.5,
        "avg_wind_chill": 47,
        "setpoint_offset": 0,
    },
    {
        "id": 79,
        "wind_chill": 48,
        "setpoint": 81.0,
        "avg_wind_chill": 48,
        "setpoint_offset": 0,
    },
    {
        "id": 80,
        "wind_chill": 49,
        "setpoint": 80.5,
        "avg_wind_chill": 49,
        "setpoint_offset": 0,
    },
    {
        "id": 81,
        "wind_chill": 50,
        "setpoint": 80.0,
        "avg_wind_chill": 50,
        "setpoint_offset": 0,
    },
    {
        "id": 82,
        "wind_chill": 51,
        "setpoint": 79.5,
        "avg_wind_chill": 51,
        "setpoint_offset": 0,
    },
    {
        "id": 83,
        "wind_chill": 52,
        "setpoint": 79.0,
        "avg_wind_chill": 52,
        "setpoint_offset": 0,
    },
    {
        "id": 84,
        "wind_chill": 53,
        "setpoint": 78.5,
        "avg_wind_chill": 53,
        "setpoint_offset": 0,
    },
    {
        "id": 85,
        "wind_chill": 54,
        "setpoint": 78.0,
        "avg_wind_chill": 54,
        "setpoint_offset": 0,
    },
    {
        "id": 86,
        "wind_chill": 55,
        "setpoint": 77.5,
        "avg_wind_chill": 55,
        "setpoint_offset": 0,
    },
    {
        "id": 87,
        "wind_chill": 56,
        "setpoint": 77.0,
        "avg_wind_chill": 56,
        "setpoint_offset": 0,
    },
    {
        "id": 88,
        "wind_chill": 57,
        "setpoint": 76.5,
        "avg_wind_chill": 57,
        "setpoint_offset": 0,
    },
    {
        "id": 89,
        "wind_chill": 58,
        "setpoint": 76.0,
        "avg_wind_chill": 58,
        "setpoint_offset": 0,
    },
    {
        "id": 90,
        "wind_chill": 59,
        "setpoint": 75.5,
        "avg_wind_chill": 59,
        "setpoint_offset": 0,
    },
    {
        "id": 91,
        "wind_chill": 60,
        "setpoint": 75.0,
        "avg_wind_chill": 60,
        "setpoint_offset": 0,
    },
    {
        "id": 92,
        "wind_chill": 61,
        "setpoint": 74.5,
        "avg_wind_chill": 61,
        "setpoint_offset": 0,
    },
    {
        "id": 93,
        "wind_chill": 62,
        "setpoint": 74.0,
        "avg_wind_chill": 62,
        "setpoint_offset": 0,
    },
    {
        "id": 94,
        "wind_chill": 63,
        "setpoint": 73.5,
        "avg_wind_chill": 63,
        "setpoint_offset": 0,
    },
    {
        "id": 95,
        "wind_chill": 64,
        "setpoint": 73.0,
        "avg_wind_chill": 64,
        "setpoint_offset": 0,
    },
    {
        "id": 96,
        "wind_chill": 65,
        "setpoint": 72.5,
        "avg_wind_chill": 65,
        "setpoint_offset": 0,
    },
    {
        "id": 97,
        "wind_chill": 66,
        "setpoint": 72.0,
        "avg_wind_chill": 66,
        "setpoint_offset": 0,
    },
    {
        "id": 98,
        "wind_chill": 67,
        "setpoint": 71.5,
        "avg_wind_chill": 67,
        "setpoint_offset": 0,
    },
    {
        "id": 99,
        "wind_chill": 68,
        "setpoint": 71.0,
        "avg_wind_chill": 68,
        "setpoint_offset": 0,
    },
    {
        "id": 100,
        "wind_chill": 69,
        "setpoint": 70.5,
        "avg_wind_chill": 69,
        "setpoint_offset": 0,
    },
    {
        "id": 101,
        "wind_chill": 70,
        "setpoint": 70.0,
        "avg_wind_chill": 70,
        "setpoint_offset": 0,
    },
    {
        "id": 102,
        "wind_chill": 71,
        "setpoint": 67.0,
        "avg_wind_chill": 71,
        "setpoint_offset": 2,
    },
    {
        "id": 103,
        "wind_chill": 72,
        "setpoint": 64.0,
        "avg_wind_chill": 72,
        "setpoint_offset": 4,
    },
    {
        "id": 104,
        "wind_chill": 73,
        "setpoint": 61.0,
        "avg_wind_chill": 73,
        "setpoint_offset": 6,
    },
    {
        "id": 105,
        "wind_chill": 74,
        "setpoint": 58.0,
        "avg_wind_chill": 74,
        "setpoint_offset": 8,
    },
    {
        "id": 106,
        "wind_chill": 75,
        "setpoint": 55.0,
        "avg_wind_chill": 75,
        "setpoint_offset": 10,
    },
    {
        "id": 107,
        "wind_chill": 76,
        "setpoint": 52.0,
        "avg_wind_chill": 76,
        "setpoint_offset": 12,
    },
    {
        "id": 108,
        "wind_chill": 77,
        "setpoint": 49.0,
        "avg_wind_chill": 77,
        "setpoint_offset": 14,
    },
    {
        "id": 109,
        "wind_chill": 78,
        "setpoint": 46.0,
        "avg_wind_chill": 78,
        "setpoint_offset": 16,
    },
    {
        "id": 110,
        "wind_chill": 79,
        "setpoint": 43.0,
        "avg_wind_chill": 79,
        "setpoint_offset": 18,
    },
    {
        "id": 111,
        "wind_chill": 80,
        "setpoint": 40.0,
        "avg_wind_chill": 80,
        "setpoint_offset": 20,
    },
    {
        "id": 112,
        "wind_chill": 81,
        "setpoint": 37.0,
        "avg_wind_chill": 81,
        "setpoint_offset": 22,
    },
    {
        "id": 113,
        "wind_chill": 82,
        "setpoint": 36.0,
        "avg_wind_chill": 82,
        "setpoint_offset": 24,
    },
    {
        "id": 114,
        "wind_chill": 83,
        "setpoint": 36.0,
        "avg_wind_chill": 83,
        "setpoint_offset": 26,
    },
    {
        "id": 115,
        "wind_chill": 84,
        "setpoint": 36.0,
        "avg_wind_chill": 84,
        "setpoint_offset": 28,
    },
    {
        "id": 116,
        "wind_chill": 85,
        "setpoint": 36.0,
        "avg_wind_chill": 85,
        "setpoint_offset": 30,
    },
    {
        "id": 117,
        "wind_chill": 86,
        "setpoint": 36.0,
        "avg_wind_chill": 86,
        "setpoint_offset": 32,
    },
    {
        "id": 118,
        "wind_chill": 87,
        "setpoint": 36.0,
        "avg_wind_chill": 87,
        "setpoint_offset": 34,
    },
    {
        "id": 119,
        "wind_chill": 88,
        "setpoint": 36.0,
        "avg_wind_chill": 88,
        "setpoint_offset": 36,
    },
    {
        "id": 120,
        "wind_chill": 89,
        "setpoint": 36.0,
        "avg_wind_chill": 89,
        "setpoint_offset": 36,
    },
    {
        "id": 121,
        "wind_chill": 90,
        "setpoint": 36.0,
        "avg_wind_chill": 90,
        "setpoint_offset": 36,
    },
    {
        "id": 122,
        "wind_chill": 91,
        "setpoint": 36.0,
        "avg_wind_chill": 91,
        "setpoint_offset": 36,
    },
    {
        "id": 123,
        "wind_chill": 92,
        "setpoint": 36.0,
        "avg_wind_chill": 92,
        "setpoint_offset": 36,
    },
    {
        "id": 124,
        "wind_chill": 93,
        "setpoint": 36.0,
        "avg_wind_chill": 93,
        "setpoint_offset": 36,
    },
    {
        "id": 125,
        "wind_chill": 94,
        "setpoint": 36.0,
        "avg_wind_chill": 94,
        "setpoint_offset": 36,
    },
    {
        "id": 126,
        "wind_chill": 95,
        "setpoint": 36.0,
        "avg_wind_chill": 95,
        "setpoint_offset": 36,
    },
    {
        "id": 127,
        "wind_chill": 96,
        "setpoint": 36.0,
        "avg_wind_chill": 96,
        "setpoint_offset": 36,
    },
    {
        "id": 128,
        "wind_chill": 97,
        "setpoint": 36.0,
        "avg_wind_chill": 97,
        "setpoint_offset": 36,
    },
    {
        "id": 129,
        "wind_chill": 98,
        "setpoint": 36.0,
        "avg_wind_chill": 98,
        "setpoint_offset": 36,
    },
    {
        "id": 130,
        "wind_chill": 99,
        "setpoint": 36.0,
        "avg_wind_chill": 99,
        "setpoint_offset": 36,
    },
    {
        "id": 131,
        "wind_chill": 100,
        "setpoint": 36.0,
        "avg_wind_chill": 100,
        "setpoint_offset": 36,
    },
    {
        "id": 132,
        "wind_chill": 101,
        "setpoint": 36.0,
        "avg_wind_chill": 101,
        "setpoint_offset": 36,
    },
    {
        "id": 133,
        "wind_chill": 102,
        "setpoint": 36.0,
        "avg_wind_chill": 102,
        "setpoint_offset": 36,
    },
    {
        "id": 134,
        "wind_chill": 103,
        "setpoint": 36.0,
        "avg_wind_chill": 103,
        "setpoint_offset": 36,
    },
    {
        "id": 135,
        "wind_chill": 104,
        "setpoint": 36.0,
        "avg_wind_chill": 104,
        "setpoint_offset": 36,
    },
    {
        "id": 136,
        "wind_chill": 105,
        "setpoint": 36.0,
        "avg_wind_chill": 105,
        "setpoint_offset": 36,
    },
    {
        "id": 137,
        "wind_chill": 106,
        "setpoint": 36.0,
        "avg_wind_chill": 106,
        "setpoint_offset": 36,
    },
    {
        "id": 138,
        "wind_chill": 107,
        "setpoint": 36.0,
        "avg_wind_chill": 107,
        "setpoint_offset": 36,
    },
    {
        "id": 139,
        "wind_chill": 108,
        "setpoint": 36.0,
        "avg_wind_chill": 108,
        "setpoint_offset": 36,
    },
    {
        "id": 140,
        "wind_chill": 109,
        "setpoint": 36.0,
        "avg_wind_chill": 109,
        "setpoint_offset": 36,
    },
    {
        "id": 141,
        "wind_chill": 110,
        "setpoint": 36.0,
        "avg_wind_chill": 110,
        "setpoint_offset": 36,
    },
    {
        "id": 142,
        "wind_chill": 111,
        "setpoint": 36.0,
        "avg_wind_chill": 111,
        "setpoint_offset": 36,
    },
    {
        "id": 143,
        "wind_chill": 112,
        "setpoint": 36.0,
        "avg_wind_chill": 112,
        "setpoint_offset": 36,
    },
    {
        "id": 144,
        "wind_chill": 113,
        "setpoint": 36.0,
        "avg_wind_chill": 113,
        "setpoint_offset": 36,
    },
    {
        "id": 145,
        "wind_chill": 114,
        "setpoint": 36.0,
        "avg_wind_chill": 114,
        "setpoint_offset": 36,
    },
    {
        "id": 146,
        "wind_chill": 115,
        "setpoint": 36.0,
        "avg_wind_chill": 115,
        "setpoint_offset": 36,
    },
    {
        "id": 147,
        "wind_chill": 116,
        "setpoint": 36.0,
        "avg_wind_chill": 116,
        "setpoint_offset": 36,
    },
]
