name: Unit tests

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main]

jobs:
  edge_server:
    name: Edge Server CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install python package manager
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run edge-server tests
        run: |
          cd edge_server
          uv sync --all-extras
          uv run pytest

  dashboard_backend:
    name: Dashboard backend pytest suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Copy template .env files
        run: |
          bash setup-env.sh
      - name: Run docker-compose to start services
        run: |
          docker compose up -d dashboard_backend edge_server

      - name: Install python package manager
        run: |
          python -m pip install --upgrade pip
          pip install uv
          pip install alembic psycopg2 uvicorn python-dotenv

      - name: Run Alembic migrations
        run: |
          cd chronos2/dashboard_backend
          alembic upgrade head

      - name: Run dashboard-backend test suite
        run: |
          cd chronos2/dashboard_backend
          uv sync --all-extras
          uv run pytest

  react-ci:
    name: Run frontend test suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install React dependencies
        run: cd chronos2/dashboard_frontend && npm install

      - name: Run Jest tests
        run: cd chronos2/dashboard_frontend && npm test -- --coverage

      - name: Build React project
        run: cd chronos2/dashboard_frontend && npm run build

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python package manager
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install React dependencies
        run: cd chronos2/dashboard_frontend && npm install

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
