name: Push to Docker image to AWS ECR and deploy to AWS EC2

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: Deployment environment to deploy to.
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'terraform/**'
  workflow_call:
    inputs:
      deployment:
        description: Development environment to deploy to. Usually `staging` or `production`
        required: true
        default: staging
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  set-deployment:
    runs-on: ubuntu-latest
    name: Set deployment
    outputs:
      deployment: ${{ steps.set-deployment.outputs.deployment }}
    steps:
      - name: Set deployment
        id: set-deployment
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' || "${{ inputs.deployment }}" == 'staging' ]]; then
            echo "deployment=staging" >> $GITHUB_OUTPUT
          else
            echo "deployment=production" >> $GITHUB_OUTPUT
          fi
          cat "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT" | grep 'deployment'

  infrastructure-modified:
    runs-on: ubuntu-latest
    name: Check for modified infrastructure
    outputs:
      modified-files: ${{ steps.set-output.outputs.modified-files }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Get modified infrastructure configuration
        id: infrastructure-modified
        uses: tj-actions/changed-files@v45
        with:
          files: |
            terraform/**

      - name: Set modified output
        id: set-output
        env:
          MODIFIED_FILES: ${{ steps.infrastructure-modified.outputs.any_modified }}
        run: |
          echo "modified-files=${MODIFIED_FILES}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: [infrastructure-modified, set-deployment]
    strategy:
      matrix:
        component: ["backend", "frontend"]
    uses: ./.github/workflows/build-docker.yml
    if: ( (github.event_name == 'pull_request' && github.event.pull_request.merged == true && needs.infrastructure-modified.outputs.modified-files != 'true' && needs.set-deployment.result == 'success') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'workflow_call') )
    secrets: inherit
    with:
      component: ${{ matrix.component }}
      deployment: ${{ needs.set-deployment.outputs.deployment }}

  docker-up:
    needs: [build-and-push, set-deployment, infrastructure-modified]
    if: ${{ always() && !cancelled() && needs.build-and-push.result == 'success'  && ( (github.event_name == 'pull_request' && github.event.pull_request.merged == 'true' && needs.infrastructure-modified.outputs.modified-files != 'true') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'push') || (github.event_name == 'workflow_call') )}}
    name: Deploy and run Docker images on EC2
    uses: ./.github/workflows/docker-up.yml
    secrets: inherit
    with:
      deployment: ${{ needs.set-deployment.outputs.deployment }}
      
