name: Deploy OpenTofu

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'terraform/**'
      - '.github/workflows/deploy-opentofu.yml'
  workflow_dispatch:
    inputs:
      deployment:
        description: Development environment to deploy to.
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'terraform/**'
      - '.github/workflows/deploy-opentofu.yml'

env:
  working_directory_parent: ./terraform
  TF_VAR_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write
  contents: read
  
jobs:
  set-deployment:
    runs-on: ubuntu-latest
    name: Set development environment
    outputs:
      deployment: ${{ steps.set-deployment.outputs.deployment }}
    steps:
      - name: Set development environment
        id: set-deployment
        run: |
          if [[ "${{ github.event_name }}" == 'workflow_dispatch' && "${{ inputs.deployment }}" == 'production' ]]; then
            echo 'deployment=production' >> "$GITHUB_OUTPUT"
          else
            echo 'deployment=staging' >> "$GITHUB_OUTPUT"
          fi
          cat "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT" | grep 'deployment'
    
  deploy-shared-resources:
    needs: [set-deployment]
    if: ${{ always() && !cancelled() && needs.set-deployment.result == 'success' && needs.set-deployment.outputs.deployment == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role-shared

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize shared resources
        working-directory: ${{ env.working_directory_parent }}/shared
        run: |
          tofu init

      - name: Plan resources
        working-directory: ${{ env.working_directory_parent }}/shared
        run: |
          tofu plan -no-color -detailed-exitcode -out=tfplan
        continue-on-error: true

      - name: Deploy shared resources
        if: ${{ github.event_name != 'push' }}
        working-directory: ${{ env.working_directory_parent }}/shared
        run: |
          tofu apply -no-color -auto-approve tfplan

  deploy-environments:
    needs: [deploy-shared-resources, set-deployment]
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && (needs.deploy-shared-resources.result == 'success' || (needs.deploy-shared-resources.result == 'skipped' && github.event_name == 'workflow_dispatch')) }}
    env:
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_additional_public_key: ${{ secrets.ADDITIONAL_PUBLIC_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role-shared

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize resources
        working-directory: ${{ env.working_directory_parent }}/${{ needs.set-deployment.outputs.deployment }}
        run: |
          tofu init

      - name: Plan resources
        working-directory: ${{ env.working_directory_parent }}/${{ needs.set-deployment.outputs.deployment }}
        run: |
          tofu plan -no-color -detailed-exitcode -out=tfplan
        continue-on-error: true

      - name: Deploy resources
        if: ${{ github.event_name != 'push' }}
        working-directory: ${{ env.working_directory_parent }}/${{ needs.set-deployment.outputs.deployment }}
        run: |
          tofu apply -no-color -auto-approve tfplan

  deploy-docker:
    needs: [deploy-environments, set-deployment]
    if: ${{ always() && !cancelled() && needs.deploy-environments.result == 'success' && github.event_name != 'push' }}
    name: Push and deploy Docker images to EC2
    uses: ./.github/workflows/deploy-docker.yml
    secrets: inherit
    with:
      deployment: ${{ needs.set-deployment.outputs.deployment }}
